### ISSUE TITLE
EPIC: Add possibility to adjust count of marks and output file name, dataset name and open file mode

### ISSUE THREAD

**Issue by MostHappyCougar** [MostHappyCougar/HDF5ImageMarker#4]
### Description
To make more ability for functional we should to add feature that make possible to set required count of marks that will be marked up for the image

This value will be placed upon `conf` section of the config.xml

Also we should add posibility to adjust:
- Output File Name
- Dataset Name
- Write mode

In case when EXISTING file opened and NO dataset introduced upon this file the dataset should be created. It is required to make more ability to create different datasets upon same file

### Config architecture example:
```
<?xml version="1.0" encoding="UTF-8"?>
<root>
	<conf>
		<img_w>2</img_w>
		<img_h>2</img_h>
		<window_size_w>16</window_size_w>
		<window_size_h>8</window_size_h>
		<source_folder>source</source_folder>
		<output_folder>output</output_folder>
		<marks_counts>5</marks_counts>
		<output_file>
			<file_name>test_suite</file_name>
			<dataset_name>Test</dataset_name>
			<write_mode>a</write_mode>
		</output_file>
	</conf>
	
	<logs>
		<log_folder>logs</log_folder>
		<import_logs>0</import_logs>
	</logs>
</root>
```
### Related Issues:
- [x] https://github.com/MostHappyCougar/HDF5ImageMarker/issues/5
- [x] https://github.com/MostHappyCougar/HDF5ImageMarker/issues/6
- [x] https://github.com/MostHappyCougar/HDF5ImageMarker/issues/7
- [x] https://github.com/MostHappyCougar/HDF5ImageMarker/issues/8
